title          = "Juicer"
subtitle       = "A Static Site Generator"
repoLink       = "https://github.com/edadma/juicer"
logo           = "images/juicer-logo-name.png"
author         = "@edadma"
authorLink     = "https://github.com/edadma"
rightsReserved = "All Rights Reserved."
license        = "ISC"
licenseLink    = "https://github.com/edadma/juicer/blob/dev/LICENSE"
